"""Turn the crowd recordings in sound/recordings/ into sound/recordings.js for the app.

Expects two recordings:
  - a stadium ambience (file name containing "stadium", "ambience" or "ambient") for the background
  - a goal reaction (file name containing "goal", "reaction" or "cheer") for goals
Both are converted to compressed AAC with macOS afconvert and embedded as base64, so the page
plays them without any network requests (this also works inside the Claude page).

Usage: python3 build_sounds.py   (then python3 build_site.py to refresh the website)
"""
import base64
import pathlib
import subprocess
import sys
import tempfile

ROOT = pathlib.Path(__file__).resolve().parent
SRC = ROOT / "sound" / "recordings"
OUT = ROOT / "sound" / "recordings.js"
AUDIO = {".wav", ".flac", ".mp3", ".m4a", ".aif", ".aiff", ".caf"}

CREDITS = """// Crowd recordings, both Creative Commons 0 (public domain), from Freesound:
//   "Soccer Stadium 02.wav" by Sandermotions (Cambuur Stadium, Leeuwarden) - https://freesound.org/s/494350/
//   "19 Football Crowd - Reaction To Goal.flac" by D.jones - https://freesound.org/s/528799/
// Generated by build_sounds.py from sound/recordings/; don't edit by hand.
"""


def pick(files, words):
    return next((f for f in files if any(w in f.name.lower() for w in words)), None)


def to_aac(src, tmp):
    out = pathlib.Path(tmp) / (src.stem + ".m4a")
    subprocess.run(["afconvert", "-f", "m4af", "-d", "aac", "-b", "96000", str(src), str(out)], check=True)
    return out.read_bytes()


def main():
    files = sorted(f for f in SRC.glob("*") if f.suffix.lower() in AUDIO) if SRC.exists() else []
    bed = pick(files, ["stadium", "ambience", "ambient"])
    goal = pick([f for f in files if f != bed], ["goal", "reaction", "cheer"])
    if not bed or not goal:
        found = ", ".join(f.name for f in files) or "nothing"
        sys.exit(f"Need a stadium ambience and a goal reaction in {SRC} (found: {found}).")
    with tempfile.TemporaryDirectory() as tmp:
        bed_b64 = base64.b64encode(to_aac(bed, tmp)).decode()
        goal_b64 = base64.b64encode(to_aac(goal, tmp)).decode()
    OUT.write_text(f'{CREDITS}window.BirdseyeCrowdAudio = {{ bed: "{bed_b64}", goal: "{goal_b64}" }};\n', encoding="utf-8")
    print(f"Background: {bed.name}")
    print(f"Goal reaction: {goal.name}")
    print(f"Wrote {OUT.relative_to(ROOT)} ({OUT.stat().st_size // 1024} KB)")


if __name__ == "__main__":
    main()
